import express from 'express';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const dataDir = path.join(root, 'data');
const dataFile = path.join(dataDir, 'projects.json');
const port = Number(process.env.PORT || 8787);
const starterFiles = [
  { path: 'index.html', content: '<main class="site-shell"><nav class="nav"><div class="wordmark">NORTHSTAR</div><div class="nav-links"><a href="#work">Work</a><a href="#about">About</a><a class="nav-cta" href="#contact">Start a project</a></div></nav><section class="hero"><div class="eyebrow">Independent digital studio · 2026</div><h1>We make brands<br><em>impossible</em> to ignore.</h1><p class="hero-copy">Northstar builds clear, magnetic identities for teams moving the culture forward.</p><a class="button" href="#work">Explore the work <span>↗</span></a></section><section id="work" class="work-grid"><article class="work-card work-card-tall"><span>01 / Identity</span><h2>Soft power<br>for hard problems.</h2><div class="orb orb-coral"></div></article><article class="work-card work-card-dark"><span>02 / Digital</span><h2>A sharper<br>point of view.</h2><div class="orb orb-lilac"></div></article><article class="work-card work-card-wide"><span>03 / Campaign</span><h2>Make room<br>for the next.</h2><div class="orb orb-blue"></div></article></section><section id="about" class="manifesto"><div class="eyebrow">The Northstar method</div><p>Small teams. Big swings. We turn the messy middle into a visual system people can feel.</p></section><footer id="contact"><div class="wordmark">NORTHSTAR</div><a href="mailto:hello@northstar.studio">hello@northstar.studio ↗</a></footer></main>' },
  { path: 'styles.css', content: ':root{font-family:Inter,Arial,sans-serif;color:#17171a;background:#f3f1ec}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0}.site-shell{max-width:1180px;margin:auto;padding:28px 42px}.nav{display:flex;justify-content:space-between;align-items:center}.wordmark{font-size:13px;letter-spacing:.17em;font-weight:800}.nav-links{display:flex;gap:28px;align-items:center;font-size:12px}.nav a{color:inherit;text-decoration:none}.nav-cta{border:1px solid #17171a;border-radius:999px;padding:10px 15px}.hero{padding:146px 0 118px;max-width:940px}.eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.16em;opacity:.58}.hero h1{font-size:clamp(58px,9vw,126px);line-height:.92;letter-spacing:-.075em;margin:24px 0 30px;font-weight:700}.hero h1 em{font-family:Georgia,serif;font-weight:400;letter-spacing:-.09em}.hero-copy{font-size:18px;line-height:1.5;max-width:390px;margin-bottom:30px}.button{display:inline-flex;gap:22px;align-items:center;background:#17171a;color:#fff;padding:15px 18px;text-decoration:none;border-radius:999px;font-size:13px}.work-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.work-card{min-height:310px;padding:24px;position:relative;overflow:hidden;border-radius:4px}.work-card span{font-size:10px;text-transform:uppercase;letter-spacing:.12em;position:relative;z-index:2}.work-card h2{font-size:36px;line-height:.95;letter-spacing:-.055em;margin-top:105px;position:relative;z-index:2}.work-card-tall{background:#f2a38d;min-height:430px}.work-card-dark{background:#191d2a;color:white}.work-card-wide{background:#c9c2f8;grid-column:1 / -1;min-height:360px}.orb{position:absolute;width:260px;height:260px;border-radius:50%;filter:blur(2px);opacity:.76;right:-35px;bottom:-85px}.orb-coral{background:#f9dbc5}.orb-lilac{background:#7065d7;right:15%;top:10%}.orb-blue{background:#678cff;width:390px;height:390px;right:13%;bottom:-200px}.manifesto{padding:170px 0 140px;display:grid;grid-template-columns:1fr 2fr;gap:20px}.manifesto p{font-size:clamp(32px,5vw,66px);line-height:.98;letter-spacing:-.06em;margin:0}.manifesto+footer,footer{border-top:1px solid #c5c1b8;padding:24px 0;display:flex;justify-content:space-between;font-size:12px}footer a{color:inherit;text-decoration:none}@media(max-width:700px){.site-shell{padding:22px}.nav-links a:not(.nav-cta){display:none}.hero{padding:110px 0 90px}.work-grid{grid-template-columns:1fr}.work-card-wide{grid-column:auto}.manifesto{display:block;padding:110px 0}.manifesto p{margin-top:28px}}' }
];
function uid(prefix){return prefix+'-'+crypto.randomUUID().slice(0,8)}
function slugify(value){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,46)||'untitled-site'}
function now(){return new Date().toISOString()}
function seed(){const created=now();return [{id:'demo',name:'Northstar Studio',slug:'northstar-studio',description:'A magnetic studio landing page',status:'published',updatedAt:created,publishedAt:created,publishedRevisionId:'rev-demo',currentRevisionId:'rev-demo',revisions:[{id:'rev-demo',label:'Initial concept',prompt:'Create a distinctive creative studio landing page.',summary:'Created the initial Northstar studio concept with a responsive editorial layout.',createdAt:created,files:starterFiles}]}]}
function load(){try{fs.mkdirSync(dataDir,{recursive:true});if(!fs.existsSync(dataFile))fs.writeFileSync(dataFile,JSON.stringify(seed(),null,2));return JSON.parse(fs.readFileSync(dataFile,'utf8'))}catch{return seed()}}
function save(projects){fs.mkdirSync(dataDir,{recursive:true});fs.writeFileSync(dataFile,JSON.stringify(projects,null,2))}
function current(project){return project.revisions.find(item=>item.id===project.currentRevisionId)||project.revisions[0]}
function applyPrompt(files,prompt){const next=files.map(file=>({...file}));const lower=prompt.toLowerCase();const css=next.find(file=>file.path==='styles.css');const html=next.find(file=>file.path==='index.html');if(css&&(lower.includes('blue')||lower.includes('ocean')))css.content=css.content.replace('#f2a38d','#8fc5d8').replace('#c9c2f8','#b9d5ef');if(css&&(lower.includes('dark')||lower.includes('black')))css.content=css.content.replace('background:#f3f1ec','background:#111319').replace('color:#17171a','color:#f6f3ed');if(css&&(lower.includes('green')||lower.includes('forest')))css.content=css.content.replace('#f2a38d','#9dc7a9').replace('#c9c2f8','#d4e4c8');if(html&&lower.includes('headline'))html.content=html.content.replace('We make brands<br><em>impossible</em> to ignore.','Ideas with<br><em>gravity.</em>');return next}
const GROQ_URL='https://api.groq.com/openai/v1/chat/completions';
const GROQ_MODEL=process.env.GROQ_MODEL||'openai/gpt-oss-20b';
const siteSchema={type:'object',properties:{summary:{type:'string'},files:{type:'array',items:{type:'object',properties:{path:{type:'string'},content:{type:'string'}},required:['path','content'],additionalProperties:false}}},required:['summary','files'],additionalProperties:false};
function isSafePath(value){return typeof value==='string'&&value.length>0&&value.length<120&&!value.startsWith('/')&&!value.includes('..')&&!value.includes('\\')&&!value.includes(':')&&(value==='index.html'||value==='styles.css'||value==='script.js'||value.startsWith('assets/'))}
function mergeGeneratedFiles(previous,generated){const output=previous.map(file=>({...file}));for(const file of generated){if(!isSafePath(file.path)||typeof file.content!=='string'||file.content.length>250000)throw new Error('Groq returned an unsafe file operation');const existing=output.find(item=>item.path===file.path);if(existing)existing.content=file.content;else output.push({path:file.path,content:file.content})}if(!output.some(file=>file.path==='index.html'))throw new Error('Generated project must include index.html');return output.slice(0,12)}
async function generateWithGroq(previous,prompt){if(!process.env.GROQ_API_KEY)return null;const response=await fetch(GROQ_URL,{method:'POST',headers:{Authorization:'Bearer '+process.env.GROQ_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({model:GROQ_MODEL,temperature:0.2,max_completion_tokens:12000,messages:[{role:'system',content:'You are Forgehouse, a careful AI website builder. Return only the requested JSON structure. Improve the current browser-rendered site based on the user instruction. You may update only index.html, styles.css, script.js, or assets/*; never return server code, package files, environment variables, credentials, iframe escape code, external forms, or navigation that attempts to access the parent window. Return complete contents only for files that need changes. Keep existing content when it already satisfies the request.'},{role:'user',content:JSON.stringify({instruction:prompt,currentFiles:previous})}],response_format:{type:'json_schema',json_schema:{name:'forgehouse_site_change',strict:true,schema:siteSchema}}})});if(!response.ok)throw new Error('Groq request failed with HTTP '+response.status);const payload=await response.json();const raw=payload.choices?.[0]?.message?.content;if(!raw)throw new Error('Groq returned an empty response');const parsed=JSON.parse(raw);return {summary:String(parsed.summary||'Applied the requested site change.'),files:mergeGeneratedFiles(previous,Array.isArray(parsed.files)?parsed.files:[])};}

const app=express();app.use(express.json({limit:'3mb'}));app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');next()});
app.get('/api/health',(req,res)=>res.json({ok:true,groqConfigured:Boolean(process.env.GROQ_API_KEY)}));
app.get('/api/projects',(req,res)=>res.json(load()));
app.post('/api/projects',(req,res)=>{const projects=load();const name=String(req.body?.name||'Untitled concept').slice(0,80);const created=now();const revision={id:uid('rev'),label:'Initial concept',prompt:'',summary:'Created a clean starter canvas ready for your first instruction.',createdAt:created,files:starterFiles};const project={id:uid('project'),name,slug:slugify(name)+'-'+Date.now().toString().slice(-4),description:String(req.body?.description||'A new AI-built website').slice(0,140),status:'draft',updatedAt:created,currentRevisionId:revision.id,revisions:[revision]};projects.unshift(project);save(projects);res.status(201).json(project)});
app.get('/api/projects/:id',(req,res)=>{const project=load().find(item=>item.id===req.params.id);if(!project)return res.status(404).json({error:'Project not found'});res.json(project)});
app.post('/api/projects/:id/generate',async(req,res)=>{const projects=load();const project=projects.find(item=>item.id===req.params.id);if(!project)return res.status(404).json({error:'Project not found'});const prompt=String(req.body?.prompt||'').trim();if(!prompt)return res.status(400).json({error:'Prompt is required'});if(prompt.length>4000)return res.status(413).json({error:'Prompt is too long'});const previous=current(project);const created=now();let result;let usedGroq=false;try{result=await generateWithGroq(previous.files,prompt);usedGroq=Boolean(result)}catch(error){console.error('[Groq]',error instanceof Error?error.message:'generation failed');result=null}if(!result)result={summary:process.env.GROQ_API_KEY?'Groq was unavailable, so a safe local fallback created this revision.':'Groq is not configured yet; a safe local fallback created this revision.',files:applyPrompt(previous.files,prompt)};const revision={id:uid('rev'),label:'AI change',prompt:prompt.slice(0,500),summary:result.summary+(usedGroq?'':' Configure GROQ_API_KEY for model-powered changes.'),createdAt:created,files:result.files};project.revisions.unshift(revision);project.currentRevisionId=revision.id;project.updatedAt=created;project.status='draft';save(projects);res.json(project)});
app.post('/api/projects/:id/revisions/:revisionId/restore',(req,res)=>{const projects=load();const project=projects.find(item=>item.id===req.params.id);if(!project)return res.status(404).json({error:'Project not found'});const target=project.revisions.find(item=>item.id===req.params.revisionId);if(!target)return res.status(404).json({error:'Revision not found'});const created=now();const revision={...target,id:uid('rev'),label:'Restored version',summary:'Restored from '+target.label+'.',createdAt:created};project.revisions.unshift(revision);project.currentRevisionId=revision.id;project.updatedAt=created;project.status='draft';save(projects);res.json(project)});
app.post('/api/projects/:id/publish',(req,res)=>{const projects=load();const project=projects.find(item=>item.id===req.params.id);if(!project)return res.status(404).json({error:'Project not found'});project.status='published';project.publishedAt=now();project.publishedRevisionId=project.currentRevisionId;project.updatedAt=project.publishedAt;save(projects);res.json(project)});
app.post('/api/projects/:id/unpublish',(req,res)=>{const projects=load();const project=projects.find(item=>item.id===req.params.id);if(!project)return res.status(404).json({error:'Project not found'});project.status='draft';delete project.publishedAt;delete project.publishedRevisionId;save(projects);res.json(project)});
app.get('/sites/:slug',(req,res)=>{const project=load().find(item=>item.slug===req.params.slug&&item.status==='published');if(!project)return res.status(404).send('<h1>Site not published</h1>');const revision=project.revisions.find(item=>item.id===project.publishedRevisionId)||current(project);const html=revision.files.find(file=>file.path==='index.html')?.content||'';const css=revision.files.find(file=>file.path==='styles.css')?.content||'';const js=revision.files.find(file=>file.path==='script.js')?.content||'';res.setHeader('Content-Security-Policy',"default-src 'self'; base-uri 'none'; object-src 'none'; form-action 'none'; connect-src 'none'; frame-ancestors 'none'; style-src 'unsafe-inline' https://fonts.googleapis.com; script-src 'unsafe-inline'; img-src 'self' data: https:; font-src https://fonts.gstatic.com https://fonts.googleapis.com");res.type('html').send('<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css+'</style></head><body>'+html+'<script>'+js+'</script></body></html>')});
const dist=path.join(root,'dist');if(fs.existsSync(dist))app.use(express.static(dist));app.get('*',(req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'Not found'});const index=path.join(dist,'index.html');if(fs.existsSync(index))return res.sendFile(index);res.status(200).send('Forgehouse is ready. Run npm run build to serve the studio.');});
app.listen(port,()=>console.log('Forgehouse server listening on '+port));
