import express from 'express';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const defaultDataDir = process.env.FORGEHOUSE_DATA_DIR || path.join(root, 'data');
const port = Number(process.env.PORT || 8787);
const starterFiles = [
  { path: 'index.html', content: '<main class="site-shell"><nav class="nav"><div class="wordmark">NORTHSTAR</div><div class="nav-links"><a href="#work">Work</a><a href="#about">About</a><a class="nav-cta" href="#contact">Start a project</a></div></nav><section class="hero"><div class="eyebrow">Independent digital studio · 2026</div><h1>We make brands<br><em>impossible</em> to ignore.</h1><p class="hero-copy">Northstar builds clear, magnetic identities for teams moving the culture forward.</p><a class="button" href="#work">Explore the work <span>↗</span></a></section><section id="work" class="work-grid"><article class="work-card work-card-tall"><span>01 / Identity</span><h2>Soft power<br>for hard problems.</h2><div class="orb orb-coral"></div></article><article class="work-card work-card-dark"><span>02 / Digital</span><h2>A sharper<br>point of view.</h2><div class="orb orb-lilac"></div></article><article class="work-card work-card-wide"><span>03 / Campaign</span><h2>Make room<br>for the next.</h2><div class="orb orb-blue"></div></article></section><section id="about" class="manifesto"><div class="eyebrow">The Northstar method</div><p>Small teams. Big swings. We turn the messy middle into a visual system people can feel.</p></section><footer id="contact"><div class="wordmark">NORTHSTAR</div><a href="mailto:hello@northstar.studio">hello@northstar.studio ↗</a></footer></main>' },
  { path: 'styles.css', content: ':root{font-family:Inter,Arial,sans-serif;color:#17171a;background:#f3f1ec}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0}.site-shell{max-width:1180px;margin:auto;padding:28px 42px}.nav{display:flex;justify-content:space-between;align-items:center}.wordmark{font-size:13px;letter-spacing:.17em;font-weight:800}.nav-links{display:flex;gap:28px;align-items:center;font-size:12px}.nav a{color:inherit;text-decoration:none}.nav-cta{border:1px solid #17171a;border-radius:999px;padding:10px 15px}.hero{padding:146px 0 118px;max-width:940px}.eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.16em;opacity:.58}.hero h1{font-size:clamp(58px,9vw,126px);line-height:.92;letter-spacing:-.075em;margin:24px 0 30px;font-weight:700}.hero h1 em{font-family:Georgia,serif;font-weight:400;letter-spacing:-.09em}.hero-copy{font-size:18px;line-height:1.5;max-width:390px;margin-bottom:30px}.button{display:inline-flex;gap:22px;align-items:center;background:#17171a;color:#fff;padding:15px 18px;text-decoration:none;border-radius:999px;font-size:13px}.work-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.work-card{min-height:310px;padding:24px;position:relative;overflow:hidden;border-radius:4px}.work-card span{font-size:10px;text-transform:uppercase;letter-spacing:.12em;position:relative;z-index:2}.work-card h2{font-size:36px;line-height:.95;letter-spacing:-.055em;margin-top:105px;position:relative;z-index:2}.work-card-tall{background:#f2a38d;min-height:430px}.work-card-dark{background:#191d2a;color:white}.work-card-wide{background:#c9c2f8;grid-column:1 / -1;min-height:360px}.orb{position:absolute;width:260px;height:260px;border-radius:50%;filter:blur(2px);opacity:.76;right:-35px;bottom:-85px}.orb-coral{background:#f9dbc5}.orb-lilac{background:#7065d7;right:15%;top:10%}.orb-blue{background:#678cff;width:390px;height:390px;right:13%;bottom:-200px}.manifesto{padding:170px 0 140px;display:grid;grid-template-columns:1fr 2fr;gap:20px}.manifesto p{font-size:clamp(32px,5vw,66px);line-height:.98;letter-spacing:-.06em;margin:0}.manifesto+footer,footer{border-top:1px solid #c5c1b8;padding:24px 0;display:flex;justify-content:space-between;font-size:12px}footer a{color:inherit;text-decoration:none}@media(max-width:700px){.site-shell{padding:22px}.nav-links a:not(.nav-cta){display:none}.hero{padding:110px 0 90px}.work-grid{grid-template-columns:1fr}.work-card-wide{grid-column:auto}.manifesto{display:block;padding:110px 0}.manifesto p{margin-top:28px}}' }
];
function uid(prefix){return prefix+'-'+crypto.randomUUID().slice(0,8)}
function now(){return new Date().toISOString()}
function slugify(value){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,46)||'untitled-site'}
function hashPassword(password){const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.scryptSync(password,salt,64).toString('hex');return {salt,hash}}
function verifyPassword(password,record){const candidate=crypto.scryptSync(password,record.salt,64);return crypto.timingSafeEqual(candidate,Buffer.from(record.hash,'hex'))}
function parseCookies(value=''){return Object.fromEntries(value.split(';').map(item=>item.trim().split('=').map(decodeURIComponent)).filter(item=>item.length===2))}
function safePath(value){return typeof value==='string'&&value.length>0&&value.length<120&&!value.startsWith('/')&&!value.includes('..')&&!value.includes('\\')&&!value.includes(':')&&(value==='index.html'||value==='styles.css'||value==='script.js'||value.startsWith('assets/'))}
function sanitizeUser(user){return user?{id:user.id,email:user.email,name:user.name}:null}
function current(project){return project.revisions.find(item=>item.id===project.currentRevisionId)||project.revisions[0]}
function applyPrompt(files,prompt){const next=files.map(file=>({...file}));const lower=prompt.toLowerCase();const css=next.find(file=>file.path==='styles.css');const html=next.find(file=>file.path==='index.html');if(css&&(lower.includes('blue')||lower.includes('ocean')))css.content=css.content.replace('#f2a38d','#8fc5d8').replace('#c9c2f8','#b9d5ef');if(css&&(lower.includes('dark')||lower.includes('black')))css.content=css.content.replace('background:#f3f1ec','background:#111319').replace('color:#17171a','color:#f6f3ed');if(css&&(lower.includes('green')||lower.includes('forest')))css.content=css.content.replace('#f2a38d','#9dc7a9').replace('#c9c2f8','#d4e4c8');if(html&&lower.includes('headline'))html.content=html.content.replace('We make brands<br><em>impossible</em> to ignore.','Ideas with<br><em>gravity.</em>');return next}
const GROQ_URL='https://api.groq.com/openai/v1/chat/completions';
const GROQ_MODEL=process.env.GROQ_MODEL||'openai/gpt-oss-20b';
const siteSchema={type:'object',properties:{summary:{type:'string'},files:{type:'array',items:{type:'object',properties:{path:{type:'string'},content:{type:'string'}},required:['path','content'],additionalProperties:false}}},required:['summary','files'],additionalProperties:false};
function mergeGeneratedFiles(previous,generated){const output=previous.map(file=>({...file}));for(const file of generated){if(!safePath(file.path)||typeof file.content!=='string'||file.content.length>250000)throw new Error('Unsafe generated file');const existing=output.find(item=>item.path===file.path);if(existing)existing.content=file.content;else output.push({path:file.path,content:file.content})}if(!output.some(file=>file.path==='index.html'))throw new Error('Generated project must include index.html');return output.slice(0,12)}
async function generateWithGroq(previous,prompt){if(!process.env.GROQ_API_KEY)return null;const response=await fetch(GROQ_URL,{method:'POST',headers:{Authorization:'Bearer '+process.env.GROQ_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({model:GROQ_MODEL,temperature:0.2,max_completion_tokens:12000,messages:[{role:'system',content:'You are Forgehouse, a careful AI website builder. Return only the requested JSON structure. Update the browser-rendered site based on the instruction. You may update only index.html, styles.css, script.js, or assets/*. Never return server code, package files, environment variables, credentials, iframe escape code, external forms, or parent-window access. Return complete contents only for files that need changes.'},{role:'user',content:JSON.stringify({instruction:prompt,currentFiles:previous})}],response_format:{type:'json_schema',json_schema:{name:'forgehouse_site_change',strict:true,schema:siteSchema}}})});if(!response.ok)throw new Error('Groq HTTP '+response.status);const payload=await response.json();const raw=payload.choices?.[0]?.message?.content;if(!raw)throw new Error('Groq returned no content');const parsed=JSON.parse(raw);return {summary:String(parsed.summary||'Applied the requested site change.'),files:mergeGeneratedFiles(previous,Array.isArray(parsed.files)?parsed.files:[])};}

export function createApp(options={}){
  const dataDir=options.dataDir||defaultDataDir;const dataFile=path.join(dataDir,'store.json');const assetDir=path.join(dataDir,'assets');
  function seed(){const created=now();return {users:[],sessions:[],projects:[{id:'demo',ownerId:null,name:'Northstar Studio',slug:'northstar-studio',description:'A magnetic studio landing page',status:'published',updatedAt:created,publishedAt:created,publishedRevisionId:'rev-demo',currentRevisionId:'rev-demo',revisions:[{id:'rev-demo',label:'Initial concept',prompt:'Create a distinctive creative studio landing page.',summary:'Created the initial Northstar studio concept with a responsive editorial layout.',createdAt:created,files:starterFiles}]}],jobs:[],assets:[],rateLimits:[]}}
  function load(){fs.mkdirSync(assetDir,{recursive:true});if(!fs.existsSync(dataFile))fs.writeFileSync(dataFile,JSON.stringify(seed(),null,2));try{return JSON.parse(fs.readFileSync(dataFile,'utf8'))}catch{return seed()}}
  function save(store){fs.mkdirSync(assetDir,{recursive:true});const temp=dataFile+'.tmp';fs.writeFileSync(temp,JSON.stringify(store,null,2));fs.renameSync(temp,dataFile)}
  function sessionUser(req){const store=load();const token=parseCookies(req.headers.cookie||'').forgehouse_session||String(req.headers.authorization||'').replace(/^Bearer /,'');const session=store.sessions.find(item=>item.token===token&&item.expiresAt>Date.now());return session?store.users.find(user=>user.id===session.userId):null}
  function auth(req,res,next){const user=sessionUser(req);if(!user)return res.status(401).json({error:'Authentication required'});req.user=user;next()}
  function setSession(res,userId){const store=load();const token=crypto.randomBytes(32).toString('hex');store.sessions=store.sessions.filter(item=>item.expiresAt>Date.now());store.sessions.push({token,userId,expiresAt:Date.now()+1000*60*60*24*14});save(store);const secure=process.env.NODE_ENV==='production'?'; Secure':'';res.setHeader('Set-Cookie','forgehouse_session='+encodeURIComponent(token)+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=1209600'+secure)}
  function clearSession(req,res){const store=load();const token=parseCookies(req.headers.cookie||'').forgehouse_session;store.sessions=store.sessions.filter(item=>item.token!==token);save(store);res.setHeader('Set-Cookie','forgehouse_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0')}
  function limit(req,res,key,max,windowMs){const store=load();const nowMs=Date.now();const identity=(req.user?.id||req.ip||'anonymous')+':'+key;store.rateLimits=store.rateLimits.filter(item=>item.expiresAt>nowMs);let record=store.rateLimits.find(item=>item.identity===identity);if(!record){record={identity,count:0,expiresAt:nowMs+windowMs};store.rateLimits.push(record)}if(record.count>=max){save(store);res.setHeader('Retry-After',Math.ceil((record.expiresAt-nowMs)/1000));res.status(429).json({error:'Rate limit reached',retryAfter:record.expiresAt});return false}record.count++;save(store);return true}
  async function runJob(jobId){const store=load();const job=store.jobs.find(item=>item.id===jobId);if(!job||job.status==='cancelled')return;job.status='running';job.startedAt=now();save(store);try{const fresh=load();const project=fresh.projects.find(item=>item.id===job.projectId);if(!project)throw new Error('Project not found');const previous=current(project);let result;let usedGroq=false;try{result=await generateWithGroq(previous.files,job.prompt);usedGroq=Boolean(result)}catch(error){console.error('[Groq]',error instanceof Error?error.message:'provider failure');result=null}const latest=load();const latestJob=latest.jobs.find(item=>item.id===jobId);if(!latestJob||latestJob.status==='cancelled')return;const target=latest.projects.find(item=>item.id===job.projectId);const revision={id:uid('rev'),label:'AI change',prompt:job.prompt.slice(0,500),summary:(result?result.summary:'Safe fallback applied; configure GROQ_API_KEY for model-powered changes.')+(usedGroq?'':' Configure GROQ_API_KEY for live Groq generation.'),createdAt:now(),files:result?result.files:applyPrompt(current(target).files,job.prompt)};target.revisions.unshift(revision);target.currentRevisionId=revision.id;target.updatedAt=revision.createdAt;target.status='draft';latestJob.status='succeeded';latestJob.finishedAt=revision.createdAt;latestJob.revisionId=revision.id;latestJob.summary=revision.summary;save(latest)}catch(error){const failed=load();const failedJob=failed.jobs.find(item=>item.id===jobId);if(failedJob){failedJob.status='failed';failedJob.finishedAt=now();failedJob.error='Generation failed safely. Retry the request.';save(failed)}}}
  const app=express();app.disable('x-powered-by');app.set('trust proxy',1);app.use(express.json({limit:'5mb'}));app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');next()});
  app.get('/api/health',(req,res)=>res.json({ok:true,groqConfigured:Boolean(process.env.GROQ_API_KEY),version:'2.0.0'}));
  app.get('/api/ready',(req,res)=>{try{load();res.json({ready:true,storage:true,groqConfigured:Boolean(process.env.GROQ_API_KEY)})}catch{res.status(503).json({ready:false,storage:false})}});
  app.get('/api/auth/me',(req,res)=>res.json({user:sanitizeUser(sessionUser(req))}));
  app.post('/api/auth/register',(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase();const password=String(req.body?.password||'');const name=String(req.body?.name||email.split('@')[0]||'Builder').trim().slice(0,80);if(!/^\\S+@\\S+\\.\\S+$/.test(email)||password.length<8)return res.status(400).json({error:'Use a valid email and a password with at least 8 characters'});const store=load();if(store.users.some(user=>user.email===email))return res.status(409).json({error:'An account already exists for this email'});const hashed=hashPassword(password);const user={id:uid('user'),email,name,passwordHash:hashed.hash,passwordSalt:hashed.salt,createdAt:now()};store.users.push(user);const demo=store.projects.find(project=>project.id==='demo'&&project.ownerId===null);if(demo)demo.ownerId=user.id;save(store);setSession(res,user.id);res.status(201).json({user:sanitizeUser(user)})});
  app.post('/api/auth/login',(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase();const password=String(req.body?.password||'');const user=load().users.find(item=>item.email===email);if(!user||!verifyPassword(password,user))return res.status(401).json({error:'Invalid email or password'});setSession(res,user.id);res.json({user:sanitizeUser(user)})});
  app.post('/api/auth/logout',(req,res)=>{clearSession(req,res);res.json({success:true})});
  app.use('/api/projects',auth);
  app.get('/api/projects',(req,res)=>{const store=load();const demo=store.projects.find(project=>project.id==='demo'&&project.ownerId===null);if(demo){demo.ownerId=req.user.id;save(store)}res.json(load().projects.filter(project=>project.ownerId===req.user.id).map(project=>({...project,revisions:project.revisions.slice(0,20)})))});
  app.post('/api/projects',(req,res)=>{if(!limit(req,res,'project-create',20,60*60*1000))return;const store=load();const name=String(req.body?.name||'Untitled concept').trim().slice(0,80);const created=now();const revision={id:uid('rev'),label:'Initial concept',prompt:'',summary:'Created a clean starter canvas ready for your first instruction.',createdAt:created,files:starterFiles};const project={id:uid('project'),ownerId:req.user.id,name:name||'Untitled concept',slug:slugify(name)+'-'+Date.now().toString().slice(-4),description:String(req.body?.description||'A new AI-built website').slice(0,140),status:'draft',updatedAt:created,currentRevisionId:revision.id,revisions:[revision]};store.projects.unshift(project);save(store);res.status(201).json(project)});
  app.get('/api/projects/:id',(req,res)=>{const project=load().projects.find(item=>item.id===req.params.id&&item.ownerId===req.user.id);if(!project)return res.status(404).json({error:'Project not found'});res.json(project)});
  app.post('/api/projects/:id/generate',(req,res)=>{if(!limit(req,res,'generation',20,15*60*1000))return;const store=load();const project=store.projects.find(item=>item.id===req.params.id&&item.ownerId===req.user.id);const prompt=String(req.body?.prompt||'').trim();if(!project)return res.status(404).json({error:'Project not found'});if(!prompt)return res.status(400).json({error:'Prompt is required'});if(prompt.length>4000)return res.status(413).json({error:'Prompt is too long'});const active=store.jobs.find(item=>item.projectId===project.id&&['queued','running'].includes(item.status));if(active)return res.status(409).json({error:'A generation is already running',job:active});const job={id:uid('job'),projectId:project.id,userId:req.user.id,prompt,status:'queued',createdAt:now()};store.jobs.unshift(job);save(store);setTimeout(()=>runJob(job.id),0);res.status(202).json({job})});
  app.get('/api/projects/:id/jobs/:jobId',(req,res)=>{const store=load();const project=store.projects.find(item=>item.id===req.params.id&&item.ownerId===req.user.id);const job=store.jobs.find(item=>item.id===req.params.jobId&&item.projectId===req.params.id&&item.userId===req.user.id);if(!project||!job)return res.status(404).json({error:'Job not found'});res.json({job,project:job.status==='succeeded'?project:null})});
  app.post('/api/projects/:id/jobs/:jobId/cancel',(req,res)=>{const store=load();const project=store.projects.find(item=>item.id===req.params.id&&item.ownerId===req.user.id);const job=store.jobs.find(item=>item.id===req.params.jobId&&item.projectId===req.params.id&&item.userId===req.user.id);if(!project||!job)return res.status(404).json({error:'Job not found'});if(['queued','running'].includes(job.status)){job.status='cancelled';job.finishedAt=now();save(store)}res.json({job})});
  app.post('/api/projects/:id/revisions/:revisionId/restore',(req,res)=>{const store=load();const project=store.projects.find(item=>item.id===req.params.id&&item.ownerId===req.user.id);if(!project)return res.status(404).json({error:'Project not found'});const target=project.revisions.find(item=>item.id===req.params.revisionId);if(!target)return res.status(404).json({error:'Revision not found'});const created=now();const revision={...target,id:uid('rev'),label:'Restored version',summary:'Restored from '+target.label+'.',createdAt:created};project.revisions.unshift(revision);project.currentRevisionId=revision.id;project.updatedAt=created;project.status='draft';save(store);res.json(project)});
  app.post('/api/projects/:id/publish',(req,res)=>{const store=load();const project=store.projects.find(item=>item.id===req.params.id&&item.ownerId===req.user.id);if(!project)return res.status(404).json({error:'Project not found'});project.status='published';project.publishedAt=now();project.publishedRevisionId=project.currentRevisionId;project.updatedAt=project.publishedAt;save(store);res.json(project)});
  app.post('/api/projects/:id/unpublish',(req,res)=>{const store=load();const project=store.projects.find(item=>item.id===req.params.id&&item.ownerId===req.user.id);if(!project)return res.status(404).json({error:'Project not found'});project.status='draft';delete project.publishedAt;delete project.publishedRevisionId;save(store);res.json(project)});
  app.post('/api/projects/:id/assets',async(req,res)=>{const store=load();const project=store.projects.find(item=>item.id===req.params.id&&item.ownerId===req.user.id);if(!project)return res.status(404).json({error:'Project not found'});if(!limit(req,res,'asset-upload',30,60*60*1000))return;const mime=String(req.body?.mimeType||'');const name=String(req.body?.name||'asset').replace(/[^a-zA-Z0-9._-]/g,'-').slice(0,100);const allowed=['image/png','image/jpeg','image/webp','image/gif'];const raw=String(req.body?.data||'').replace(/^data:[^;]+;base64,/,'');if(!allowed.includes(mime)||!raw||raw.length>4*1024*1024)return res.status(400).json({error:'Only PNG, JPEG, WebP, or GIF assets up to 3 MB are supported'});const id=uid('asset');const fileName=id+'-'+name;fs.writeFileSync(path.join(assetDir,fileName),Buffer.from(raw,'base64'));const asset={id,projectId:project.id,ownerId:req.user.id,name,mimeType:mime,size:fs.statSync(path.join(assetDir,fileName)).size,fileName,createdAt:now()};store.assets.push(asset);save(store);res.status(201).json({asset,url:'/api/assets/'+id})});
  app.get('/api/assets/:id',(req,res)=>{const store=load();const asset=store.assets.find(item=>item.id===req.params.id);if(!asset)return res.status(404).end();const project=store.projects.find(item=>item.id===asset.projectId);const user=sessionUser(req);if(!project||(!project.publishedRevisionId&&(!user||user.id!==asset.ownerId)))return res.status(404).end();res.type(asset.mimeType).sendFile(path.join(assetDir,asset.fileName))});
  app.get('/sites/:slug',(req,res)=>{const project=load().projects.find(item=>item.slug===req.params.slug&&item.status==='published');if(!project)return res.status(404).send('<h1>Site not published</h1>');const revision=project.revisions.find(item=>item.id===project.publishedRevisionId)||current(project);const html=revision.files.find(file=>file.path==='index.html')?.content||'';const css=revision.files.find(file=>file.path==='styles.css')?.content||'';const js=revision.files.find(file=>file.path==='script.js')?.content||'';res.setHeader('Content-Security-Policy',"default-src 'self'; base-uri 'none'; object-src 'none'; form-action 'none'; connect-src 'none'; frame-ancestors 'none'; style-src 'unsafe-inline' https://fonts.googleapis.com; script-src 'unsafe-inline'; img-src 'self' data: https:; font-src https://fonts.gstatic.com https://fonts.googleapis.com");res.type('html').send('<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css.replaceAll('</style','<\\/style')+'</style></head><body>'+html+'<script>'+js.replaceAll('</script','<\\/script')+'</script></body></html>')});
  app.use((error,req,res,next)=>{console.error('[request]',error?.message||error);res.status(500).json({error:'Unexpected server error'})});return app
}

if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))createApp().listen(port,()=>console.log('Forgehouse server listening on '+port));
